version: '2'
volumes:
  unms_config:
  db:
  dbcfg:
  data:
  log:
  cert:
  init:
  dir:
  run:
networks:
  unifi:
services:
  unms:
    image: nico640/docker-unms:latest
    restart: always
    ports:
      - 80:80
      - 443:443
      - 2055:2055/udp
    environment:
      - TZ=Americas/Phoenix
    volumes:
      - 'unms_config:/config'
  mongo:
    image: mongo:3.6
    container_name: unifi_mongo
    networks:
      - unifi
    restart: always
    volumes:
      - db:/data/db
      - dbcfg:/data/configdb
  unifi_controller:
    image: 'jacobalberty/unifi:5.14.23'
    container_name: unifi_controller
    depends_on:
      - mongo
    networks:
      - unifi
    restart: always
    volumes:
      - dir:/unifi
      - data:/unifi/data
      - log:/unifi/log
      - cert:/unifi/cert
      - init:/unifi/init.d
      - run:/var/run/unifi
      # # Mount local folder for backups and autobackups
      # - ./backup:/unifi/data/backup
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
    ports:
      - '3478:3478/udp' # STUN
      - '6789:6789/tcp' # Speed test
      - '8080:8080/tcp' # Device/ controller comm.
      - '8443:8443/tcp' # Controller GUI/API as seen in a web browser
      - '8880:8880/tcp' # HTTP portal redirection
      - '8843:8843/tcp' # HTTPS portal redirection
      - '10001:10001/udp' # AP discovery
  logs:
    image: bash
    container_name: unifi_logs
    depends_on:
      - unifi_controller
    command: bash -c 'tail -F /unifi/log/*.log'
    restart: always
    volumes:
      - log:/unifi/log