version: '2'
volumes:
  unifi-config:
services:
  unifi-controller:
    image: linuxserver/unifi-controller:latest
    # There are multiple reasons why we use host networking:
    #
    # 1. To avoid having to keep a large number of ports in sync. https://help.ubnt.com/hc/en-us/articles/218506997
    # 2. To avoid performance issues when publishing many ports. https://forums.balena.io/t/large-number-of-forwarded-udp-ports-break-the-device/36364
    # 3. To avoid having to manually set an externally accessible device hostname. https://github.com/linuxserver/docker-unifi-controller/tree/148d990f25f2b9a55c99b64635ea629e5052b8e7#application-setup
    network_mode: host
    restart: unless-stopped
    volumes:
      - "unifi-config:/config"