version: '2'
volumes:
  unms_config:
services:
  unms:
    image: nico640/docker-unms:latest
    restart: always
    ports:
      - 80:80
      - 443:443
      - 2055:2055/udp
    environment:
      - TZ=Americas/Phoenix
    volumes:
      - 'unms_config:/config'
